language: node_js
node_js:
  - "node"

before_install:
  - npm install
  - npm run start.ci

script:
  - npm run unit.test.coverage
  - npm run unit.test.mutation
  - node_modules/.bin/newman run tests/api/collection.json
